//
//  SpacesWorker.swift
//  SpaceClient
//
//  Created by Mahmud CIKRIK on 20.12.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class RocketsWorker {
    func fetchRockets(completion: @escaping ((_ response: [RocketsResponseModel], _ error: CNetworkError?) -> Void)) {
        CNetwork.shared.execute(requestRoute: CNetworkRouter.rockets, responseModel: [RocketsResponseModel].self) { result in
            switch result {
            case .success(let rockets):
                completion(rockets, nil)
            case .failure(let error):
                completion([], error)
            }
        }
    }
}
