//
//  SpacesModels.swift
//  SpaceClient
//
//  Created by Mahmud CIKRIK on 20.12.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Rockets {
  // MARK: Use cases
  
  enum FetchRockets {
    struct Request {
    }
    
    struct Response {
        var rockets: [RocketsResponseModel]
    }
    
    struct ViewModel {
        struct DisplayedRocket {
            var rocketId: String
            var rocketName: String
            var rocketDescription: String
            var rocketImage: String
        }
        
        var displayedRockets: [DisplayedRocket]
    }
  }
}
